# Technically not needed but useful to have the AWS CLI available for testing and debugging
---
- name: Download AWS CLI v2
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'
  become: true
  become_user: root

- name: Unzip AWS CLI v2
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: true
  become: true
  become_user: root

- name: Install AWS CLI v2
  ansible.builtin.command:
    cmd: "./aws/install --update"
  args:
    chdir: "/tmp"
  become: true
  become_user: root

- name: Clean up AWS CLI v2 installation files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/awscliv2.zip"
    - "/tmp/aws"
  become: true
  become_user: root

- name: Ensure .aws directory exists for postgres user
  ansible.builtin.file:
    path: /var/lib/postgresql/.aws
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  become: true
  become_user: root
