---
- name: Install common packages
  ansible.builtin.apt:
    name: "{{ postgresql_necessary_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install postgresql-common
  ansible.builtin.apt:
    name: postgresql-common
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Run PostgreSQL PGDG repository setup script
  ansible.builtin.shell: "echo | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh"
  args:
    creates: /etc/apt/sources.list.d/pgdg.list
  become: true
  when: ansible_os_family == 'Debian'

- name: Install PostgreSQL 
  ansible.builtin.apt:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: true
  when: not ansible_check_mode and ansible_os_family == 'Debian'

