---
- name: Install PostgreSQL
  ansible.builtin.include_tasks: install-postgresql.yml

- name: Configure PostgreSQL
  ansible.builtin.include_tasks: configure-postgresql.yml

- name: Configure PostgreSQL SSL
  ansible.builtin.include_tasks: configure-postgresql-ssl.yml

- name: Configure pgBackRest
  ansible.builtin.include_tasks: configure-pgbackrest.yml

- name: Configure Postgres Metrics Exporter
  ansible.builtin.include_tasks: configure-postgres-metrics-exporter.yml

- name: Install AWS CLI
  ansible.builtin.include_tasks: install-aws-cli.yml
