cluster:
  apiServer:
    extraArgs:
      feature-gates: UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true
  controllerManager:
    extraArgs:
      "bind-address": "0.0.0.0"

  etcd:
    extraArgs:
      "listen-metrics-urls": "http://0.0.0.0:2381"

  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml

  network:
    cni:
      name: none

  proxy:
    disabled: true

  scheduler:
    extraArgs:
      "bind-address": "0.0.0.0"

machine:
  install:
    disk: /dev/sda

  files:
    - content: |
        [metrics]
          address = "0.0.0.0:11234"
      path: /etc/cri/conf.d/20-customization.part
      op: create

  sysctls:
    user.max_user_namespaces: "11255"

  kubelet:
    extraConfig:
      featureGates:
        UserNamespacesSupport: true
        UserNamespacesPodSecurityStandards: true
    extraArgs:
      rotate-server-certificates: true
---
apiVersion: v1alpha1
kind: TrustedRootsConfig
name: custom-ca
certificates: |-
  -----BEGIN CERTIFICATE-----
  MIIF0jCCA7qgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgY4xCzAJBgNVBAYTAkRF
  MQwwCgYDVQQIDANOUlcxEDAOBgNVBAoMB0hvbWVsYWIxDjAMBgNVBAsMBUthbGxl
  MSIwIAYDVQQDDBlIb21lbGFiIEludGVybWVkaWF0ZSBDQSAxMSswKQYJKoZIhvcN
  AQkBFhxrYWplZXBhbi5rYW5kZWVwYW5AZ21haWwuY29tMB4XDTI1MDUyNDIyMjEy
  OFoXDTM1MDUyMjIyMjEyOFowYTELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05SVzEQ
  MA4GA1UECgwHSG9tZWxhYjEOMAwGA1UECwwFS2FsbGUxIjAgBgNVBAMMGUhvbWVs
  YWIgSW50ZXJtZWRpYXRlIENBIDIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
  AoICAQDo2YH764eumpkxnKpwL9PYh+e5aDgrJwPcjoKVkgOT4Mg8VBrzX08Svd1T
  P9lGtmat7nsByVDkb+A8ODAEzovaOB0VdHO4s/EzFQOe+BBls6cRTaVOU7sbzFmD
  oQ5beetrPKgmWRybUMPwaBRWKskp1N8O/9OWUb8C3dpQptK8ZvAQdFnG4WVk9Tgc
  SBxzMv5M9jYENNyT25ypLCvcqnx+wuxm5j+4efpgygfti1oeXHWYWWUkmqDPn+u+
  EQkHbb9aW5FmZ2SmmgaRu3/0CHzOL5gbboIXvjVP76Sndqx98i5xwVrupmca7fB+
  YPIMBrggTc651bRdoZH0E81JPKP5AD8nvTqHXZv75eb1TwWsQHW0a/EomaAesHg2
  +NfEAQs/JLrowviPoiJD+x5TqhRPoL2DoYZZXruH6IpWiEVKl+engN4lD07/DhX4
  p7smLpvkSR9ZsPyuvgaNhOozAh4bW2zDF54gzWw+E7GD34NHP5hPROKOQ7JYLFsF
  Nyc8B0Y6TNglNGzInaH+/phHqQTsoe5u56kCmt4z3RT+/GExsMEMd5inftsXQ4X3
  1LklQ/IOShRgKRpyCyd1PFNbyzU9+kWFb4VhcNf2Enbgl9aUmyg3nFe5T1fq30F9
  je0FEgfdy/4NtUoqndDxKSuDwtM1fAsq+gnvXJICOs5VbRFCAwIDAQABo2YwZDAd
  BgNVHQ4EFgQUuTJIJ0H3FI6xQUynaYFoPC+hmvwwHwYDVR0jBBgwFoAUrOkwjYmu
  nDT+9VQBMJnUrCp26+QwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMC
  AYYwDQYJKoZIhvcNAQELBQADggIBAE0ODvHwTxsCFHnycfCgNg36fJR1RYKoKCsr
  SXrjIsl3z4PRxboCn28M74zie8E1yk06Qwkx9pSXBM7CfrHKmdTfysPPH3Q2b7PR
  fC1oNkO0+81+3R1bD6eN+Ih2a5xz8Dh9HDIY1EvPmPYD5r9wgDbhNSnSz55ucFHT
  nJBr3Pc0idhlR0R/9gf9FsyPiKWyW1u61G0tuoRtrAjGTTgTrX23gG3kgw2c3frD
  1iNyc5Z5doX08CCzJkf0wbjOtH2yvVNPN2y7RjGpGnFUurVIIM7UEuLNrue8lOLh
  2F4PVlcFbLdUt/4JeUvQCuuqWw8GKZ8u2kJe71KdyJiOKpoEthqrMemS85GTeLsC
  2LMU8DmJzlhYo4NeJ6rRbaMFPKNlfIOE83dIpTSxnQB2+NRj3RcGp7GM3TNFE+FE
  2DpSft9B13/bhiKA5vAwSPMTtRYItF1NBjwA0V56m9UeQ9JSSNxSUes1SgNW1X8p
  82R2xHlENyfUug28D4U2DbqQLNNOqqEtGmmSG9QXisvcWe5E8+n+6j394pnFPNhY
  D4dovBhSCS/K9yVRYYsxJQAdeFZkSKQA6vzQJadAM/5ws6r89BfzyK2hm/ULE3tY
  Q7wzSOrbVHpehuK1i3fT309FB1JLUmRaKwZ8xknXHC9fRw9JeV9DGiQ8JVDfFlbC
  1RrawCxO
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIGBjCCA+6gAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgZQxCzAJBgNVBAYTAkRF
  MQwwCgYDVQQIDANOUlcxDjAMBgNVBAcMBUVzc2VuMRAwDgYDVQQKDAdIb21lbGFi
  MQ4wDAYDVQQLDAVLYWxsZTEYMBYGA1UEAwwPSG9tZWxhYiBSb290IENBMSswKQYJ
  KoZIhvcNAQkBFhxrYWplZXBhbi5rYW5kZWVwYW5AZ21haWwuY29tMB4XDTI1MDUy
  NDIyMjEyNloXDTM1MDUyMjIyMjEyNlowgY4xCzAJBgNVBAYTAkRFMQwwCgYDVQQI
  DANOUlcxEDAOBgNVBAoMB0hvbWVsYWIxDjAMBgNVBAsMBUthbGxlMSIwIAYDVQQD
  DBlIb21lbGFiIEludGVybWVkaWF0ZSBDQSAxMSswKQYJKoZIhvcNAQkBFhxrYWpl
  ZXBhbi5rYW5kZWVwYW5AZ21haWwuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
  MIICCgKCAgEA3yDcqx7n8xOT5HzVQ4EvT17HpQsaKTGAyhfaxtD/mAhX+BDKdFop
  8Z0p9QTAKWHVyRKotZstOoxDhyB9/7Gv+d9EjMhpEMNb1Pp4UfjOw/vdYmsJ6KAF
  Ekaov1VOBAzVN62HNoQZngvTRKD5zQogSjm2QQJOOCuKJpP3K6Ki8WrdeQaTQpRj
  kO/7zOZR3ZGwoEHqFkLarY+9R+pL7TeFRQqD0gjEgPTUzQm5dLqrrpwrw+53oYEc
  ntFGG5SaFlXKyQ5+1r+9jAylIYFvwFMKSUHKqdaADCcIrj/y6CnXSx1bacuW9ovG
  fJudar74iBhDga06c8m6FEpSWqDAIN4/aQpLz8o7iX6ctUYleN3Hkln9thqqczw9
  U8C3xA0/GQvk8GZmC2ADVge1W+8Pxn6c8+CmTu0VvPNxzYIxK050r7cNmBh4NIXe
  R8C4U8znW+TP+dyRPuOuRO1XyCKRa/1hJVzuAP1CWVdkZid5mbkk51INqPFo9WOc
  xRmrOXb5BJoj+wHDvTci/CY6HdOxrNJL+9uXp0D7EhA+nweh+uTVwvhvEQVCVNm3
  zagcYh5uchCNyPe1JdSwsAB3NMytsdvWekL5wu0kaBFimp+nkskiGm3yxp0d0nZm
  JaMmw52Iq0creqWjxenaTCo6pFuUBNINmD2eDMw0rA+z7eYy//heaZ8CAwEAAaNm
  MGQwHQYDVR0OBBYEFKzpMI2Jrpw0/vVUATCZ1KwqduvkMB8GA1UdIwQYMBaAFBLG
  JyvVzrraKxl7/a5dAav9ru9mMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/
  BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQA4rPVUMXB8O7gqGf52ngbRb80/qBYv
  GUjTz9fGESK0/Z//8LqosePUqE0U6mQh1kVAudvtTnDLLJoH0O5zUVudnAf8+NFi
  68a/nFtGMOwLzk55Ed2GE88muurSH20nZFrkngMZrR0bffXHoWdIUtzSXIN/uY/d
  5vplcr9wvNaIwXVoFqOPmEsrIJVD9irudkr0MV3LRQyP2Gae/FDPz0CHaePtLaKs
  GkuLbFPCv4PXLTDYtVwFYbLWuhTPadwKdmfwCiV5+3iT2R77uSrFhgHe8sgxLW2r
  5yWfgoNpfqE2B6WqM7NvvO7juX54H68WZajDg4Zrnr9x2eczW+b46PMyDa/tDm50
  9iITTTt78KwJkmpKy84LdM2bkqSXj9ihF1sn6O/6GMYhxJrS6eBKQ7Bgjt3So5zx
  +H/nR9B9hA4NtgAAV6AAZLV14AOszECIh23r2GFg5wgXeDXOARuYZ0ZGnn7Ru+0q
  a6BVKjSkMRjso8uFTnlTq3PyzCl6PMBoaCe7GoRVKdeVk3uF4ncg+cgMM7WZel4V
  oLMPRDhhoENEEq4UA3uytv0WaKmXrR34D03ETxeuaycBe0ozzSm+VtMJXny4ydyS
  3W6+NlEYoNUfpDJNvZyBpjgMLLHqScIxnsmtqRUZJUJQ089Uqkl35Ycby812n7rk
  7iCbyOEFPPRvog==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIGGzCCBAOgAwIBAgIUbhiEeWkIXaDKDWPC+YMtERFgp/IwDQYJKoZIhvcNAQEL
  BQAwgZQxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxDjAMBgNVBAcMBUVzc2Vu
  MRAwDgYDVQQKDAdIb21lbGFiMQ4wDAYDVQQLDAVLYWxsZTEYMBYGA1UEAwwPSG9t
  ZWxhYiBSb290IENBMSswKQYJKoZIhvcNAQkBFhxrYWplZXBhbi5rYW5kZWVwYW5A
  Z21haWwuY29tMB4XDTI1MDUyNDIyMjEyNloXDTQ1MDUxOTIyMjEyNlowgZQxCzAJ
  BgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxDjAMBgNVBAcMBUVzc2VuMRAwDgYDVQQK
  DAdIb21lbGFiMQ4wDAYDVQQLDAVLYWxsZTEYMBYGA1UEAwwPSG9tZWxhYiBSb290
  IENBMSswKQYJKoZIhvcNAQkBFhxrYWplZXBhbi5rYW5kZWVwYW5AZ21haWwuY29t
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsC7DBrQYKPrpQileyPQH
  c2zhjbBR62RwThTutMs01pbMdAFcivuNKSkEliScfvJsv8V7PBn0jTSrdgFkeZj2
  Hsn/6B4dfzOw+7KDIALufdq78C3s97kuEvxl0xkOD4lFZFUGFLLKy+qMhAaHenAk
  WeujdIASjUl67Gil6Pm5Wf2TK4yTnlqhyqCS5nPc93kLWFkEVVSbpr5ZSZLTw14S
  xnn3o3rGYuv72JZPIAaoNwZDBZ1XMsRfHLgIBq6HZNQpTqDYdF/YpeXkLpRf2WaX
  vJ5aX8rL4lXyZqmrLbViJhD9GKHXEIEKrbx8Gd6iFYuLfWFr3RpQwjJ7hftB9cc6
  NBKyj+tbhh1asuUfLsiKMqBcydT2SZhEDlFOsA5WX3y46+1JyGZ8mAbwxYyRlOPD
  lnHJdLTdp2XOmkORH0mVc/1cBmmkaVEt5xFraaRtf1QHuRiFuYpRNMH/a/4vMtOY
  KtXkWL+l51pczBXGE2qwfIlasGRgAcDbAmRq9s2JZX9dcmA+k9miqgzho1OLM9yt
  P3AuANRas5uTihNJdrugjnp5o2kVn5dQqJNI0Wm/drnGCxqITYmlnPD227Fw54Pr
  5YlTDBUAC3jHoiL1luESbJsvSWCg+H1gDCTTWO/OvHLHFjerPg+rx+yu4yKe8ceY
  2jnKjF9NCfk4tw1DIQ4VKisCAwEAAaNjMGEwHQYDVR0OBBYEFBLGJyvVzrraKxl7
  /a5dAav9ru9mMB8GA1UdIwQYMBaAFBLGJyvVzrraKxl7/a5dAav9ru9mMA8GA1Ud
  EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQAm
  UyjN+uSOXDPEbnbjdgPaIDDMexRGCNRN+KRAWU2J2pKkWmlIkl8aCJ/1tvCXSfvx
  6L5hYTSXt4Kx07x+cAgQijB3J3W5iM4TJ4tS85t+kuIyHqxTWtvfZtkR1gJnzUFF
  kApPY7vjqG2GteSwHkojGCMAnPp37Zxow1SJlPKJdLk/K6ZJgg05p3NKFOv/oEWG
  U5qBz8AmbrDaReK0lBKa24O3gf4JAsxkDLgL+ARHC3Tvrl7H3gTtse6ynJm8haPH
  7GPzXckFLMXv3KHRRzU9JwZP+FCz+A+U/jw2lYSkR9M3AIk+g6cRV41epSULrgtM
  74tkTLZWSKR+1pzAjWrvK3XwRlLKuusyBwaJD/wKGZmY8wQRXiiXNgptx8LXaCUD
  Jbjh/3D8XGsF57WiXJzIImHidMv9YD3VPdCvAT+VwW2P0FfgK1C6IPX83g66pibY
  T9RX3RGqO1KbuLDLt+NJJRomYUuuuAh6MBeaDyjxNfKokeLALln8nYCyh/zhUJnF
  0Pp4QK0oIpuqH3FUbgaIqOyvOPKApykS7hiX4wLBFe4rquISHOsU8DLMSM1j+UhZ
  XpLniraazu44k76jSxV3tcOSiQjRaHTy1iM/ooJvf3OfUGt32nvTD2gbQ1GgfTNL
  qE4NIHeWXDqcqBtEERcnqK413BIzKrL9yLDKkVYtOg==
  -----END CERTIFICATE-----
