ansible_python_interpreter: /usr/bin/python3
ansible_network_os: vyos
ansible_connection: network_cli
ansible_user: vyos

# ansible_ssh_private_key_file: /workspaces/homelab/keys/homelab
ansible_ssh_pass: vyos
