defaults: &defaults
  ansible_connection: ssh
  ansible_ssh_private_key_file: "~/.ssh/homelab"
  ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

all:
  hosts:
    vyos:
      ansible_host: 192.168.0.10
    storage:
      ansible_host: 10.10.30.10
      ansible_user: ubuntu
      <<: *defaults
    bastion:
      ansible_host: 10.10.100.10
      ansible_user: root
      <<: *defaults

  children:
    vms:
      hosts:
        bastion:
        storage:
    minio:
      hosts:
        storage:
    postgresql:
      hosts:
        storage:
    kubernetes_nodes:
      hosts:
