---
- name: Install SSH key
  vyos.vyos.vyos_config:
    lines:
      - set system login user {{ ansible_user }} authentication public-keys '{{ ansible_user }}.key1' type {{ vyos_ssh_config.key_type }}
      - set system login user {{ ansible_user }} authentication public-keys {{ ansible_user }}.key1 key '{{ (lookup('env', "PUBLIC_KEY") | split(' '))[1] }}'
    save: true

- name: Disable password authentication
  vyos.vyos.vyos_config:
    lines:
      - set service ssh disable-password-authentication
    save: true
  when: vyos_ssh_config.disable_password_authentication
