postgresql_necessary_packages:
  - git
  - build-essential
  - libssl-dev
  - libreadline-dev 
  - zlib1g-dev

postgresql_version: '17'

postgresql_packages: 
  - postgresql-{{ postgresql_version }}

postgresql_listen_addresses: '*'
postgresql_port: 5432

postgresql_aws_region: 'eu-west-1'
postgresql_aws_endpoint: 's3.storage.home.arpa:9000'
postgresql_aws_ca_bundle: "/usr/local/share/ca-certificates/root_ca.crt"

postgresql_gpg_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

postgresql_certs_cert: "{{ role_path }}/../../pki/intermediate-ca-2/certs/home-arpa.crt"
postgresql_certs_ca: "{{ role_path }}/../../pki/intermediate-ca-2/intermediate-ca-2-chain.pem"
postgresql_certs_key: "{{ role_path }}/../../pki/intermediate-ca-2/private/home-arpa.key"

postgresql_aws_bucket: 'backups'

postgresql_exporter_user: 'postgres_exporter'
postgresql_exporter_version: 0.17.1
postgresql_exporter_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgresql_exporter_version }}/postgres_exporter-{{ postgresql_exporter_version }}.linux-amd64.tar.gz"
postgresql_exporter_port: "9187"

postgresql_max_connections: 1000

postgresql_pgbackrest_stanza: 'main'

# pgBackRest retention configuration
postgresql_retention_full: 3
postgresql_retention_diff: 5
postgresql_retention_archive: 7

# pgBackRest performance
postgresql_backup_process_max: 2

# pgBackRest backup schedule configuration
postgresql_backup_full_hour: "2"
postgresql_backup_full_minute: "0"
postgresql_backup_incr_hours: "*/4"
postgresql_backup_incr_minute: "0"
