# Handlers which are notified if a critical change occurs
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl -p
  become: true
