---
- name: Copy Environment Variable File
  ansible.builtin.template:
    src: files/minio.env.j2
    dest: /etc/default/minio
    owner: root
    group: root
    mode: "0644"
  vars:
    minio_root_user: "{{ lookup('env', 'MINIO_ROOT_USER') }}"
    minio_root_password: "{{ lookup('env', 'MINIO_ROOT_PASSWORD') }}"