---
- name: Create Certs Directory
  ansible.builtin.file:
    path: "{{ minio_certs_dir }}"
    state: directory
    mode: "0700"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"

- name: Copy Certs
  ansible.builtin.copy:
    src: "{{ minio_certs_cert }}"
    dest: "{{ minio_certs_dir }}/public.crt"
    mode: "0600"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"

- name: Copy Key
  ansible.builtin.copy:
    src: "{{ minio_certs_key }}"
    dest: "{{ minio_certs_dir }}/private.key"
    mode: "0600"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
