---
- name: Set inotify max_user_watches
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^fs.inotify.max_user_watches"
    line: "fs.inotify.max_user_watches = {{ common_inotify_max_user_watches }}"
    state: present
    mode: "0644"
  notify: Reload sysctl
  when: inventory_hostname in groups['kubernetes_nodes']

- name: Ensure inotify max_user_watches is set
  ansible.builtin.sysctl:
    name: fs.inotify.max_user_watches
    value: "{{ common_inotify_max_user_watches }}"
    state: present
    reload: true
  when: inventory_hostname in groups['kubernetes_nodes']

- name: Set inotify max_user_instances
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^fs.inotify.max_user_instances"
    line: "fs.inotify.max_user_instances = {{ common_inotify_max_user_instances }}"
    state: present
    mode: "0644"
  notify: Reload sysctl
  when: inventory_hostname in groups['kubernetes_nodes']

- name: Ensure inotify max_user_instances is set
  ansible.builtin.sysctl:
    name: fs.inotify.max_user_instances
    value: "{{ common_inotify_max_user_instances }}"
    state: present
    reload: true
  when: inventory_hostname in groups['kubernetes_nodes']
