# Contains the variables for the common role

# Common Packages
common_packages:
  - nano
  - curl
  - wget
  - htop
  - qemu-guest-agent

# SSH Configuration
common_security_ssh_config_path: /etc/ssh/sshd_config
common_security_sshd_name: ssh
common_security_sshd_state: restarted
common_security_sshd_enabled: true
common_ssh_port: 22
common_security_ssh_config_template: sshd_config.j2

# Inotify Configuration
common_inotify_max_user_watches: 524288
common_inotify_max_user_instances: 8192
