# This playbook sets up a VyOS router with basic configurations. The following commands need to be run on the VyOS device before applying this plan:
# - install image
# - configure
# - set interfaces ethernet eth0 address 192.168.0.10/24
# - set service ssh port '22'
# - set protocols static route 0.0.0.0/0 next-hop 192.168.0.1
# - set interfaces ethernet eth0 address dhcpv6
# - set interfaces ethernet eth0 description 'WAN'
# - commit
# - save

### Homelab Ansible Playbook ###

- name: Setup VyOS
  hosts: vyos
  gather_facts: false
  roles:
    - vyos

- name: Setup VyOS Firewall
  hosts: vyos
  gather_facts: false
  roles:
    - vyos_firewall
